name = "{{crate_name}}"
main = "build/worker/shim.mjs"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cargo install -q worker-build && worker-build --release"

# Uncomment to enable Durable Objects support if needed
# [durable_objects]
# bindings = [
#   { name = "MCP_OBJECT", class_name = "MyMCP" }
# ]

# [migrations]
# [[migrations]]
# tag = "v1"
# new_sqlite_classes = ["MyMCP"]

[observability]
enabled = true 